config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :debits
  resources :months
  resources :years

  get '/debits/update_paid/:id', to: 'debits#update_paid', as: :update_paid

  get '/owner/get_debit_total/:id', to: 'owner#total', as: :get_debit_total_per_owner
  get '/debit/get_debit_total', to: 'debits#total', as: :get_debit_total

  post '/debit/change_owner', to: 'debits#change_owner', as: :change_owner

  root 'years#index'
end

app/models/month.rb
# frozen_string_literal: true

class Month < ApplicationRecord
  before_save :transform_name

  MONTH_NAMES = {
    'JANEIRO' => 0,
    'FEVEREIRO' => 1,
    'MARÇO' => 2,
    'MARCO' => 2,
    'ABRIL' => 3,
    'MAIO' => 4,
    'JUNHO' => 5,
    'JULHO' => 6,
    'AGOSTO' => 7,
    'SETEMBRO' => 8,
    'OUTUBRO' => 9,
    'NOVEMBRO' => 10,
    'DEZEMBRO' => 11
  }.freeze
  validates :name, presence: { message: ' deve ser informado' }

  belongs_to :user
  belongs_to :year
  has_many :debit, dependent: :destroy

  def transform_name
    return '' if name.nil?

    name.upcase!
  end

  def total
    debits_not_paid.map(&:price).compact.inject(:+)
  end

  def total_per_owner
    debits_per_owner = []

    debits_not_paid.group_by(&:owner_id).each do |key, value|
      debits_per_owner << {
        owner: Owner.find(key).name,
        total: value.map(&:price).inject(:+)
      }
    end

    debits_per_owner
  end

  def debits_not_paid
    debits_not_paid = debit.map { |d| d unless d.paid }

    debits_not_paid.compact
  end
end

app/controllers/months_controller.rb
# typed: true

class MonthsController < ApplicationController
  before_action :set_month, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /months or /months.json
  def index; end

  # GET /months/1 or /months/1.json
  def show
    @db_owners = Owner.all

    @owners = []

    @db_owners.each do |owner|
      debits_per_owner_and_month = Debit.all.where(month_id: params[:id], owner_id: owner.id)

      if debits_per_owner_and_month.empty?
        nil
      else
        @owners << owner
      end
    end

    @owners
  end

  # GET /months/new
  def new
    @month = Month.new
  end

  # GET /months/1/edit
  def edit
    @year_id = params[:year_id]
  end

  # POST /months or /months.json
  def create
    respond_to do |format|
      @month = Month.new({}.merge(month_params, { user_id: current_user.id }))

      if @month.save
        format.html { redirect_to months_path, notice: 'Mês foi criado com sucesso' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /months/1 or /months/1.json
  def update
    respond_to do |format|
      if @month.update(month_params)
        format.html { redirect_to year_path(params[:year_id]), notice: 'Mês foi atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @month }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @month.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /months/1 or /months/1.json
  def destroy
    @month.destroy

    respond_to do |format|
      format.html { redirect_to months_url, notice: 'Mês foi excluido com sucesso' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_month
    @month = Month.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def month_params
    params.require(:month).permit(:name)
  end
end

app/helpers/months_helper.rb
# frozen_string_literal: true

module MonthsHelper
  # @param first [Month]
  # @param second [Month]
  def self.sort_by_name(first, second)
    Month::MONTH_NAMES[first.name.split[0]] <=> Month::MONTH_NAMES[second.name.split[0]]
  end
end

app/views/months/_debit_per_owner.html.erb
<div class="bg-blue-700 p-2 rounded-xl text-white" >
  <a href="#" class="flex items-center justify-between mb-2" data-controller="debit" data-debit-target="clickarea" data-action="click->debit#toggle">
    <div class="flex items-center gap-2">
      <h2 id="debit_title">
        <%= debit[0].capitalize %>
      </h2>

      <svg data-debit-target="arrowicon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 25 25" width="15" height="15">
        <g id="Downv">
        <polygon points="12.5 18 2 7.707 2.707 7 12.5 16.586 22.293 7 23 7.707 12.5 18" style="fill:#FFF"/>
        </g>
      </svg>
    </div>

    <h2>
      <span class="text-gray-300">Total:</span>

      <span id="total_debit-<%= debit[0] %>">
        <%= number_to_brl(debit[1].select {|e| !e.paid }.sum { |e| e.price })  %>
      </span>
    </h2>
  </a>

  <div class="flex flex-col gap-2">
    <% debit[1].each do |d| %>
      <div class="flex flex-row" draggable="true" data-controller="drag" data-drag-target="debit" data-action="dragstart->drag#dragStart dragend->drag#dragEnd drop->drag#drop dragenter->drag#dragEnter dragleave->drag#dragLeave dragover->drag#dragOver" data-info="<%= {owner_id: d.owner_id}.to_json %>">
        <a href="#" class="flex flex-row items-center justify-between bg-white w-full text-black rounded-xl px-2 py-1" data-controller="debit" data-debit-target="payable" data-info="<%= {debit_title: d.title, id: d.id, month_id: month.id, update_paid_url: nil, owner_id: d.owner_id}.to_json %>" data-action="click->debit#pay">
          <span><%= number_to_brl(d.price)  %></span>

          <div class="w-24 <%= d.paid ? "bg-green-300" : "bg-yellow-300" %> text-center text-xs rounded-xl">
            <%= d.paid ? 'Pago' : 'Pendente' %>
          </div>
        </a>

        <%= link_to debit_path(d, month_id: month.id), data: { "turbo-method": :delete } do %>
          <%= render "layouts/delete_icon", color: 'red' %>
        <% end %>

        <%= link_to edit_debit_path(d, month_id: month.id) do %>
          <%= render 'layouts/edit_icon', color: 'white' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/months/_form.html.erb
<%= form_with(model: month, class: "contents", url: month_path(month, year_id: year_id)) do |form| %>
  <% if month.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(month.errors.count, "erro") %> impediu que o mês fosse salvo:</h2>

      <ul>
        <% month.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.text_field :name, placeholder: "Informe o nome do mês", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit submit_button, class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/months/_owner.html.erb
<%= render 'layouts/card' do %>
  <div class="flex flex-col gap-2">
    <%= render "layouts/card_header", initials: owner.initials, label: "Pagante:", title: owner.name.capitalize %>

    <% owner.group_by_same_title(month.id).each do |debit| %>
      <%= render 'months/debit_per_owner', month: month, debit: debit %>
    <% end %>
  </div>

  <div class="mt-10">
    <span class="text-gray-500 font-light uppercase">Total:</span>

    <h3 id="total_owner-<%= owner.id %>" class="font-semibold">
      <%= number_to_brl(owner.debit_not_paid(month.id).sum { |e| e.price }) %>
    </h3>
  </div>
<% end %>

app/views/months/edit.html.erb
<%= render 'layouts/header' %>

<%= render 'layouts/container' do %>
  <h1 class="font-bold text-4xl">Atualizando mes</h1>

  <%= render "form", month: @month, year_id: @year_id, submit_button: "Atualizar mês" %>
<% end %>

app/views/months/show.html.erb
<%= render 'layouts/header', path: year_path(@month.year_id) %>

<%= render 'layouts/container' do %>
  <div class="w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render 'layouts/header_title', title: "Débitos referente ao mês #{@month.name.capitalize}", button_text: "+ Adicionar Transação", path: new_debit_path(month_id: @month.id) %>

    <div class="w-full flex flex-wrap gap-20">
      <% @owners.each do |owner| %>
        <% unless owner.debit.where(month_id: @month.id).empty? %>
          <%= render 'months/owner', owner: owner, month: @month %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>