config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :debits
  resources :months
  resources :years

  get '/debits/update_paid/:id', to: 'debits#update_paid', as: :update_paid

  get '/owner/get_debit_total/:id', to: 'owner#total', as: :get_debit_total_per_owner
  get '/debit/get_debit_total', to: 'debits#total', as: :get_debit_total

  post '/debit/change_owner', to: 'debits#change_owner', as: :change_owner

  root 'years#index'
end

app/models/year.rb
# frozen_string_literal: true

class Year < ApplicationRecord
  has_many :month
  belongs_to :user
end

app/controllers/years_controller.rb
# frozen_string_literal: true

class YearsController < ApplicationController
  before_action :authenticate_user!

  def index
    render inertia: 'index', props: {
      events: Year.all.where(user_id: current_user.id)
    }
  end

  def new
    @year = Year.new
  end

  def show
    @year = Year.find(params[:id])
    @months = Month.all.where(year_id: params[:id], user_id: current_user.id).sort do |a, b|
      MonthsHelper.sort_by_name(a, b)
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @year.update(year_params)
        format.html { redirect_to years_path, notice: 'Ano foi atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @year }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @year.destroy

    respond_to do |format|
      format.html { redirect_to years_path, notice: 'Ano foi excluido com sucesso' }
    end
  end

  def create
    respond_to do |format|
      @year = Year.new({}.merge(year_params, { user_id: current_user.id }))

      create_months_by_year(@year)

      if @year.save
        format.html { redirect_to year_path(@year.id), notice: 'Ano foi criado com sucesso' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def create_months_by_year(year)
    Month::MONTH_NAMES.each_key do |month|
      year.month.build(name: month, user_id: current_user.id).save
    end
  end

  # Only allow a list of trusted parameters through.
  def year_params
    params.require(:year).permit(:name)
  end
end

app/helpers/year_helper.rb
module YearHelper
end

app/views/years/_form.html.erb
<%= form_with(model: year, class: "contents") do |form| %>
  <div class="my-5">
    <%= form.text_field :name, type: :year, placeholder: "Informe o ano", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit submit_button, class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/years/edit.html.erb
<%= render 'layouts/header' %>

<%= render 'layouts/container' do %>
  <h1 class="font-bold text-4xl">Atualizando o ano</h1>

  <%= render "form", year: @year, submit_button: "Atualizar ano" %>
<% end %>

app/views/years/index.html.erb
<%= render 'layouts/header' %>

<%= render 'layouts/container' do %>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= render 'layouts/header_title', title: "Listagem de anos", button_text: "Adicionar um novo ano", path: new_year_path %>

  <% unless @years.empty? %>
    <div class="w-full flex flex-wrap">
      <% @years.each do |year| %>
        <%= link_to year_path(year) do %>
          <div class="h-full mb-10 ml-10">
            <%= render 'layouts/card' do %>
              <%= render "layouts/card_header", initials: year.name, label: "Ano: ", title: year.name, text_size: 'text-3xl' %>

              <div class="flex items-start justify-start">
                <%= link_to year_path(year), data: { "turbo-method": :delete }, class: "mr-5" do %>
                  <%= render 'layouts/delete_icon', color: 'black' %>
                <% end %>

                <%= link_to edit_year_path(year) do %>
                  <%= render 'layouts/edit_icon', color: 'black' %>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/years/new.html.erb
<%= render 'layouts/header' %>

<%= render 'layouts/container' do %>
  <h1 class="font-bold text-4xl">Novo ano</h1>

  <%= render "form", year: @year, submit_button: "Criar ano" %>

  <%= link_to 'Voltar', years_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
<% end %>

app/views/years/show.html.erb
<%= render 'layouts/header' %>

<%= render 'layouts/container' do %>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= render 'layouts/header_title', title: "Listagem do ano #{@year.name}", path: new_month_path %>

  <% unless @months.empty? %>
    <div class="w-full flex flex-wrap">
      <% @months.each do |month| %>
        <%= link_to month_path(month) do %>
          <div class="h-full mb-10 ml-10">
            <%= render 'layouts/card' do %>
              <%= render "layouts/card_header", initials: month.name[0].upcase, label: "Nome do mês:", title: month.name.capitalize %>

              <% unless month.debit.empty? %>
                <h2 class="text-xl">
                  <span class="text-lg text-gray-400">
                    Total do mês:
                  </span>
                  <%= number_to_brl(month.total) %>
                </h2>

                <% month.total_per_owner.each do |d| %>
                  <h2 class="text-xl">
                    <span class="text-lg text-gray-400">
                      Total do pagante <%= d[:owner].capitalize %>:
                    </span>
                    <%= number_to_brl(d[:total]) %>
                  </h2>
                <% end %>
              <% end %>

              <div class="flex items-start justify-start">
                <%= link_to month_path(month), data: { "turbo-method": :delete }, class: "mr-5" do %>
                  <%= render 'layouts/delete_icon', color: 'black' %>
                <% end %>

                <%= link_to edit_month_path(month, year_id: @year.id) do %>
                  <%= render 'layouts/edit_icon', color: 'black' %>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>