config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :debits
  resources :months
  resources :years

  get '/debits/update_paid/:id', to: 'debits#update_paid', as: :update_paid

  get '/owner/get_debit_total/:id', to: 'owner#total', as: :get_debit_total_per_owner
  get '/debit/get_debit_total', to: 'debits#total', as: :get_debit_total

  post '/debit/change_owner', to: 'debits#change_owner', as: :change_owner

  root 'years#index'
end

app/views/layouts/_card.html.erb
<div class="min-w-[400px] max-w-md h-full p-4 flex flex-col justify-between gap-2 bg-white my-2 rounded-xl p-2 drop-shadow-md">
  <%= yield %>
</div>

app/views/layouts/_card_header.html.erb
<div class="flex flex-col gap-2">
  <div class="w-full flex items-center gap-4 mb-4">
    <div class="-ml-8 -mt-8 flex-2 w-20 h-20 bg-blue-700 rounded-xl flex items-center justify-center">
      <span class="text-white <%= text_size ||= "text-4xl" %>"><%= initials %></span>
    </div>

    <div class="-mt-2 flex-1 w-full flex flex-col">
      <span class="text-gray-500 font-light"><%= label %></span>

      <span class="text-3xl"><%= title %></span>

      <hr />
    </div>
  </div>
</div>

app/views/layouts/_container.html.erb
<div class="mx-12 mt-28 w-full">
  <%= yield %>
</div>

app/views/layouts/_delete_icon.html.erb
<svg width="30" height="30" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" clip-rule="evenodd" d="M6 7C6.55228 7 7 7.44772 7 8V19C7 19.5523 7.44772 20 8 20H16C16.5523 20 17 19.5523 17 19V8C17 7.44772 17.4477 7 18 7C18.5523 7 19 7.44772 19 8V19C19 20.6569 17.6569 22 16 22H8C6.34315 22 5 20.6569 5 19V8C5 7.44772 5.44772 7 6 7Z" fill="<%= color %>"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M10 8C10.5523 8 11 8.44772 11 9V17C11 17.5523 10.5523 18 10 18C9.44772 18 9 17.5523 9 17V9C9 8.44772 9.44772 8 10 8Z" fill="<%= color %>"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M14 8C14.5523 8 15 8.44772 15 9V17C15 17.5523 14.5523 18 14 18C13.4477 18 13 17.5523 13 17V9C13 8.44772 13.4477 8 14 8Z" fill="<%= color %>"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M4 5C4 4.44772 4.44772 4 5 4H19C19.5523 4 20 4.44772 20 5C20 5.55228 19.5523 6 19 6H5C4.44772 6 4 5.55228 4 5Z" fill="<%= color %>"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M8 3C8 2.44772 8.44772 2 9 2H15C15.5523 2 16 2.44772 16 3C16 3.55228 15.5523 4 15 4H9C8.44772 4 8 3.55228 8 3Z" fill="<%= color %>"/>
</svg>

app/views/layouts/_edit_icon.html.erb
<svg width="30" height="30" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  <path fill="<%= color %>" d="M20.548,3.452a1.542,1.542,0,0,1,0,2.182L12.912,13.27,9.639,14.361l1.091-3.273,7.636-7.636A1.542,1.542,0,0,1,20.548,3.452ZM4,21H19a1,1,0,0,0,1-1V12a1,1,0,0,0-2,0v7H5V6h7a1,1,0,0,0,0-2H4A1,1,0,0,0,3,5V20A1,1,0,0,0,4,21Z"/>
</svg>

app/views/layouts/_header.html.erb
<nav class="w-full flex px-12 py-6 bg-white fixed top-0 left-0 drop-shadow-md z-50 justify-between items-center">
  <%= link_to "Planerino", path ||= years_path, class: "text-2xl text-blue-700 font-medium" %>

  <% if current_user %>
    <div class="flex items-center gap-5 font-medium text-lg">
      Usuário ativo: <%= current_user.email.split('@')[0] %>
      <%= link_to destroy_user_session_path, data: {"turbo-method": :delete } do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32"><title>37-User</title><g id="_37-User" data-name="37-User"><path d="M10,10V8A6,6,0,0,1,22,8v2a1,1,0,0,0,1,1v2h2V11a2,2,0,0,0-1-1.73V8A8,8,0,0,0,8,8V9.27A2,2,0,0,0,7,11v2a2,2,0,0,0,1,1.75,8.07,8.07,0,0,0,4,6.16v1.39L4.7,25c-.91.23-4.7,1.37-4.7,4v2a1,1,0,0,0,1,1H15V30H2V29c0-.78,1.92-1.7,3.24-2l.11,0,8-3A1,1,0,0,0,14,23V20.31a1,1,0,0,0-.57-.9A6,6,0,0,1,10,14a1,1,0,0,0-1-1V11A1,1,0,0,0,10,10Z"/><path d="M31.71,22.29l-3-3-1.41,1.41L28.59,22H21v2h7.59l-1.29,1.29,1.41,1.41,3-3A1,1,0,0,0,31.71,22.29Z"/><path d="M23,27a1,1,0,0,1-1,1H19V18h3a1,1,0,0,1,1,1v1h2V19a3,3,0,0,0-3-3H18a1,1,0,0,0-1,1V29a1,1,0,0,0,1,1h4a3,3,0,0,0,3-3V26H23Z"/></g></svg>
      <% end %>
    </div>
  <% end %>
</nav>

app/views/layouts/_header_title.html.erb
<div class="w-full flex flex-row items-center mb-10">
  <div>
    <h1 class="text-3xl mb-4"><%= title %></h1>

    <% if defined?(button_text) %>
      <%= link_to button_text, path, class: "bg-blue-700 px-4 py-2 rounded-xl text-white" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planerino</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      If using a .jsx or .tsx entrypoint, add the extension:
        vite_javascript_tag 'application.jsx'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->

  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>